language: php
php:
- 5.6
- 7.0
- 7.1
- hhvm
- nightly
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
before_install:
  - composer self-update
install:
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
after_success:
    - bash <(curl -s https://codecov.io/bash)
